en: "en"
vn: "vi"
link1: https://www.railstutorial.org/
link2: ttps://www.michaelhartl.com/
link3: https://www.railstutorial.org/help
link4: https://www.railstutorial.org/book
validates:
  name: 50
  email: 255
  password: 6
userhelp:
  size: 80
railspng: rails.png
sesssion_check: "1"
